package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"time"

	ar "github.com/vonbai/autoresearch"
	"gopkg.in/yaml.v3"
)

// Init generates a goalx.yaml template in the project root.
func Init(projectRoot string, args []string) error {
	opts, err := parseStartInitArgs(args)
	if err != nil {
		return err
	}
	objective := opts.Objective
	mode := opts.Mode
	parallel := opts.Parallel
	name := opts.Name

	if name == "" {
		name = ar.Slugify(objective)
	}

	baseCfg, _, err := ar.LoadRawBaseConfig(projectRoot)
	if err != nil {
		return fmt.Errorf("load base config: %w", err)
	}
	cfg := *baseCfg
	cfg.Name = name
	cfg.Mode = mode
	cfg.Objective = objective
	cfg.Parallel = parallel
	cfg.Sessions = nil
	cfg.DiversityHints = nil
	ar.ApplyPreset(&cfg)

	// Mode-specific defaults
	if mode == ar.ModeResearch {
		reportFile := "report.md"
		cfg.Target = ar.TargetConfig{
			Files:    []string{reportFile},
			Readonly: []string{"."},
		}
		cfg.Harness = ar.HarnessConfig{Command: fmt.Sprintf("test -s %s && echo 'ok'", cfg.Target.Files[0])}
		// Apply research strategies
		if len(opts.Strategies) > 0 {
			hints, err := ar.ResolveStrategies(opts.Strategies)
			if err != nil {
				return err
			}
			cfg.DiversityHints = hints
		} else if parallel >= 2 {
			defaults := ar.DefaultStrategies(parallel)
			hints, _ := ar.ResolveStrategies(defaults)
			cfg.DiversityHints = hints
		}
	} else {
		if len(cfg.Target.Files) == 0 {
			cfg.Target = ar.TargetConfig{
				Files: []string{"TODO: specify directories to modify"},
			}
		}
		if cfg.Harness.Command == "" {
			cfg.Harness = ar.HarnessConfig{Command: "TODO: build + test command"}
		}
	}

	// Apply context from --context flag
	if len(opts.ContextPaths) > 0 {
		contextFiles, err := DiscoverContextFiles(opts.ContextPaths)
		if err != nil {
			return fmt.Errorf("discover context: %w", err)
		}
		cfg.Context = ar.ContextConfig{Files: contextFiles}
	}

	cfg.Budget = ar.BudgetConfig{MaxDuration: 6 * time.Hour}

	outPath := filepath.Join(projectRoot, "goalx.yaml")
	data, err := yaml.Marshal(&cfg)
	if err != nil {
		return err
	}

	header := "# goalx.yaml — generated by goalx init\n# engine/model/master inherited from ~/.autoresearch/config.yaml and .autoresearch/config.yaml\n"
	if err := os.WriteFile(outPath, append([]byte(header), data...), 0644); err != nil {
		return err
	}

	fmt.Printf("Generated %s\n", outPath)
	fmt.Printf("  name: %s\n", name)
	fmt.Printf("  mode: %s\n", mode)
	if mode == ar.ModeDevelop && (len(cfg.Target.Files) == 0 || cfg.Target.Files[0] == "TODO: specify directories to modify" || cfg.Harness.Command == "TODO: build + test command") {
		fmt.Println("\n  ⚠ Edit goalx.yaml: fill target.files and harness.command")
	}
	fmt.Println("\n  Next: vim goalx.yaml && goalx start")
	return nil
}
