package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"time"

	ar "github.com/vonbai/autoresearch"
	"gopkg.in/yaml.v3"
)

// Init generates a goalx.yaml template in the project root.
func Init(projectRoot string, args []string) error {
	opts, err := parseStartInitArgs(args)
	if err != nil {
		return err
	}
	objective := opts.Objective
	mode := opts.Mode
	parallel := opts.Parallel
	name := opts.Name

	if name == "" {
		name = ar.Slugify(objective)
	}

	baseCfg, _, err := ar.LoadRawBaseConfig(projectRoot)
	if err != nil {
		return fmt.Errorf("load base config: %w", err)
	}
	cfg := *baseCfg
	cfg.Name = name
	cfg.Mode = mode
	cfg.Objective = objective
	cfg.Parallel = parallel
	cfg.Sessions = nil
	cfg.DiversityHints = nil
	ar.ApplyPreset(&cfg)

	// Mode-specific defaults
	if mode == ar.ModeResearch {
		cfg.Target = ar.TargetConfig{
			Files:    []string{"report.md"},
			Readonly: []string{"."},
		}
		cfg.Harness = ar.HarnessConfig{Command: "test -s report.md && echo 'ok'"}
		// Auto-assign research strategies for parallel sessions
		if parallel >= 2 {
			strategies := []string{
				"Depth-first: Pick the single most impactful area and go as deep as possible. Run experiments, measure things, trace code paths end-to-end. Prefer one thoroughly verified finding over five shallow ones.",
				"Breadth-first + adversarial: Scan all dimensions quickly, then focus on finding problems, bugs, design flaws, and counter-examples. Challenge the project's assumptions. Look for what could go wrong.",
			}
			if parallel <= len(strategies) {
				cfg.DiversityHints = strategies[:parallel]
			} else {
				cfg.DiversityHints = strategies
			}
		}
	} else {
		if len(cfg.Target.Files) == 0 {
			cfg.Target = ar.TargetConfig{
				Files: []string{"TODO: specify directories to modify"},
			}
		}
		if cfg.Harness.Command == "" {
			cfg.Harness = ar.HarnessConfig{Command: "TODO: build + test command"}
		}
	}

	cfg.Budget = ar.BudgetConfig{MaxDuration: 6 * time.Hour}

	outPath := filepath.Join(projectRoot, "goalx.yaml")
	data, err := yaml.Marshal(&cfg)
	if err != nil {
		return err
	}

	header := "# goalx.yaml — generated by goalx init\n# engine/model/master inherited from ~/.autoresearch/config.yaml and .autoresearch/config.yaml\n"
	if err := os.WriteFile(outPath, append([]byte(header), data...), 0644); err != nil {
		return err
	}

	fmt.Printf("Generated %s\n", outPath)
	fmt.Printf("  name: %s\n", name)
	fmt.Printf("  mode: %s\n", mode)
	if mode == ar.ModeDevelop && (len(cfg.Target.Files) == 0 || cfg.Target.Files[0] == "TODO: specify directories to modify" || cfg.Harness.Command == "TODO: build + test command") {
		fmt.Println("\n  ⚠ Edit goalx.yaml: fill target.files and harness.command")
	}
	fmt.Println("\n  Next: vim goalx.yaml && goalx start")
	return nil
}
